export {default as Header} from './Header/Header';
export {default as Footer} from './Footer/Footer';
export {default as Team} from './Team/Team';
export {default as Blog} from './Blog/Blog';
export {default as Hero} from './Hero/Hero';
export {default as Testimonial} from './Testimonial/Testimonial';
export {default as Contact} from './Contact/Contact';
export {default as WhyChoose} from './WhyChoose/WhyChoose';
export {default as Work} from './Work/Work';
